### ISSUE TITLE
Cannot run maskrcnn_benchmark and ros at the same time

### ISSUE THREAD

**Issue by Tdogb** [weigao95/mrcnn_ros#1]
Since ros and anaconda are not able to be run at the same time, is there any way to use this package?

This is the error I get if I try to run the python scripts in this package. Catkin_make does not work inside of an anaconda environment and rospy does not exist inside of this environment either. 
` python nodes/mrcnn_segment_server.py 
Traceback (most recent call last):
  File "nodes/mrcnn_segment_server.py", line 26, in <module>
    from mrcnn_ros.srv import *
ModuleNotFoundError: No module named 'mrcnn_ros'
`
Other places on the internet mention how to use ros and anaconda on the same system, but none have mentioned how to do it simultaneously.

@weigao95 How did you fix this problem?

**Comment by Tdogb** [comment]
This is the error
`Traceback (most recent call last):
  File "src/mrcnn_ros/nodes/mrcnn_segment_server.py", line 26, in <module>
    from mrcnn_ros.srv import *
ModuleNotFoundError: No module named 'mrcnn_ros'`

**Comment by Tdogb** [comment]
Update:
Here are the steps I took to fix this:
After commenting out the export line from anaconda in .bashrc. I run
`
source /opt/ros/kinetic/setup.bash`
`. ~/catkin_ws/devel/setup.bash`
`roslaunch mrcnn_ros mrcnn.launch
`
The python script **WILL NOT** work on it's own, it must be run through roslaunch.
Note: change the directories in launch/mrcnn.launch to match your own.

Sorry for adding this issue, but hopefully it may help someone in the future

**Comment by weigao95** [comment]
Hi,

Sorry for the late reply. I recommend installing maskrcnn using the python interpreter with ros (not the one in conda).

If you really want a standalone environment, you might consider `virtualenv`.
